=== giacomomarchioro/phdthesis/jupyter notebook/data.dtd
<!-- data.dtd

SML: Surface Markup Language - version: alpha
There are five major elements in this DTD: Part, Process, Measurement Conditions, Data File, Analysis Data
-->
<!ELEMENT DATA (PART?,PROCESS?,MEASUREMENT?,DATAFILE,ANALYSIS)>

<!--
Part information
	PART_NAME: required. Name of a part
	PART_DATE: optional. Date when a part was made
	PART_MANUFACTURER: optional. Manufacturer who made the part
      PART_DESCRIPTION: optional. Description of the part
	PART_ADDITIONAL_INFO: optional. Additional part information 
-->
<!ELEMENT PART (PART_NAME,PART_DATE?,PART_MANUFACTURER?,PART_DESCRIPTION?,PART_ADDITIONAL_INFO?)>
<!ELEMENT PART_NAME (#PCDATA)>
<!ELEMENT PART_DATE (#PCDATA)>
<!ELEMENT PART_MANUFACTURER (#PCDATA)>
<!ELEMENT PART_DESCRIPTION (#PCDATA)>
<!ELEMENT PART_ADDITIONAL_INFO (#PCDATA)>

<!--
Process information
	PROCESS_NAME: required. Name of the process
	PROCESS_DESCRIPTION: optional. Description of the process
	PROCESS_DATE: required. Date of the process
      PROCESS_TEMPERATURE: optional. Temperature
	PROCESS_DEPTH_CUT: optional. Depth of cut
	PROCESS_TOOL_SPEED: optional. Tool Speed
	PROCESS_TOOL_LIFE: optional. Tool Life
	PROCESS_ADDITIONAL_INFO: optional. Additional process information
-->
<!ELEMENT PROCESS (PROCESS_NAME, PROCESS_DESCRIPTION?,PROCESS_DATE?,PROCESS_TEMPERATURE?,PROCESS_DEPTH_CUT?,PROCESS_TOOL_SPEED?,PROCESS_TOOL_LIFE?,PROCESS_ADDITIONAL_INFO?)>
<!ELEMENT PROCESS_NAME (#PCDATA)>
<!ELEMENT PROCESS_DESCRIPTION (#PCDATA)>
<!ELEMENT PROCESS_DATE (#PCDATA)>
<!ELEMENT PROCESS_TEMPERATURE (#PCDATA)>
<!ELEMENT PROCESS_DEPTH_CUT (#PCDATA)>
<!ELEMENT PROCESS_TOOL_SPEED (#PCDATA)>
<!ELEMENT PROCESS_TOOL_LIFE (#PCDATA)>
<!ELEMENT PROCESS_ADDITIONAL_INFO (#PCDATA)>

<!--
Measurement information
	MEASUREMENT_INSTRUMENT_TYPE: required. Type of the instrument measures the part
	MEASUREMENT_TEMPERATURE: optional. measurement temperature
	MEASUREMENT_TIP_RADIUS: optional. Tip radius value
	MEASUREMENT_TIP_ANGLE: optional. Angle of the spherical portion of the probe in degrees
	MEASUREMENT_TIP_FORCE: optional. tip force value
	MEASUREMENT_VERTICAL_DIGITIZATION: optional. Vertical Digitization
	MEASUREMENT_HORIZONTAL_DIGITIZATION: optional. Horizontal Digitization
	MEASUREMENT_DRIVE_SPEED: optional. drive speed in mm/s
	MEASUREMENT_PROBE_RANGE: optional. probe range
	MEASUREMENT_OFFSET_mm: optional. Offset of the start of the measurement in mm from the origin
	MEASUREMENT_LAST_CALIBRATION: optional. Date and time of last calibration
	MEASUREMENT_DATE: optional. date when the part was measured
	MEASUREMENT_ADDITIONAL_INFO: optional. Additional measurement information
-->
<!ELEMENT MEASUREMENT (MEASUREMENT_INSTRUMENT_TYPE, MEASUREMENT_TEMPERATURE?, MEASUREMENT_TIP_RADIUS?, MEASUREMENT_TIP_ANGLE?,MEASUREMENT_TIP_FORCE?, MEASUREMENT_VERTICAL_DIGITIZATION?, MEASUREMENT_HORIZONTAL_DIGITIZATION?, MEASUREMENT_DRIVE_SPEED?, MEASUREMENT_PROBE_RANGE?, MEASUREMENT_OFFSET_mm?,MEASUREMENT_LAST_CALIBRATION?,MEASUREMENT_DATE?, MEASUREMENT_ADDITIONAL_INFO?)>
<!ELEMENT MEASUREMENT_INSTRUMENT_TYPE (#PCDATA)>
<!ELEMENT MEASUREMENT_TEMPERATURE (#PCDATA)>
<!ELEMENT MEASUREMENT_TIP_RADIUS (#PCDATA)>
<!ELEMENT MEASUREMENT_TIP_FORCE (#PCDATA)>
<!ELEMENT MEASUREMENT_TIP_ANGLE (#PCDATA)>
<!ELEMENT MEASUREMENT_VERTICAL_DIGITIZATION (#PCDATA)>
<!ELEMENT MEASUREMENT_HORIZONTAL_DIGITIZATION (#PCDATA)>
<!ELEMENT MEASUREMENT_DRIVE_SPEED (#PCDATA)>
<!ELEMENT MEASUREMENT_PROBE_RANGE (#PCDATA)>
<!ELEMENT MEASUREMENT_OFFSET_mm (#PCDATA)>
<!ELEMENT MEASUREMENT_LAST_CALIBRATION (#PCDATA)>
<!ELEMENT MEASUREMENT_DATE (#PCDATA)>
<!ELEMENT MEASUREMENT_ADDITIONAL_INFO (#PCDATA)>

<!--
Data File information
	FILENAME: required. Data file name
	UNITS: required. units m, mm, um, nm
	NUMPOINTS: required. Number of data points
	SPACING: required. Spacing between two data points in x direction
	KCAL: optional. Calibration constant KCAL (micron/mv).
	DATA_TYPE: optional. Indicate data file is 2D or 3D
	POSITION_NO: optional. Label where a profile is taken on a surface
	TRACE_NO: optional. Label number of trace
	DATA_POINT_VALUES: required. values of data points
-->
<!ELEMENT DATAFILE (FILENAME,UNITS, NUMPOINTS,SPACING,KCAL?,POSITION_NO?,TRACE_NO?,DATA_TYPE?,DATA_POINT_VALUES)>
<!ELEMENT FILENAME (#PCDATA)>
<!ELEMENT UNITS (#PCDATA)>
<!ELEMENT NUMPOINTS (#PCDATA)>
<!ELEMENT SPACING (#PCDATA)>
<!ELEMENT KCAL (#PCDATA)>
<!ELEMENT DATA_TYPE (#PCDATA)>
<!ELEMENT POSITION_NO (#PCDATA)>
<!ELEMENT TRACE_NO (#PCDATA)>
<!ELEMENT DATA_POINT_VALUES (#PCDATA)>

<!--
Analysis Data information
	CURVATURE_REMOVAL: optional. Information ragarding least square curve fitting
	FILTER: optional. Filtering information
	STATISTICAL_ANALYSIS: optional. PSD or Correlation information
-->
<!ELEMENT ANALYSIS (CURVATURE_REMOVAL?, FILTER?, STATISTICAL_ANALYSIS?)>

<!--
Curvature removal information
	LSQ_COEFF: required. Least Square Cofficients
-->
<!ELEMENT CURVATURE_REMOVAL (LSQ_COEFF)>
<!ELEMENT LSQ_COEFF (#PCDATA)>

<!--
Filtering information
	FILTER_TYPE: required. Filter Type (Gaussian or Two RC filter)
	SHORT_CUTOFF: optional. Short Cutoff
	LONG_CUTOFF: required. Long Cutoff
	METHOD: required. Filtering implementation method such as covolution, recursive, or FFT
	LSQ_REMOVED_PROFILE: optional. Least Square Removed Profile
	SHORT_CUTOFF_PROFILE: optional. Primary Profile
	RAW_PROFILE: optional. Total Profile
	ROUGHNESS: required. Roughness Profile
	WAVINESS: required. Waviness Profile
-->
<!ELEMENT FILTER (FILTER_TYPE,SHORT_CUTOFF?,LONG_CUTOFF,UNITS,METHOD,SHORT_CUTOFF_PROFILE?,LSQ_REMOVED_PROFILE?, RAW_PROFILE?,ROUGHNESS,WAVINESS)>
<!ELEMENT FILTER_TYPE (#PCDATA)>
<!ELEMENT SHORT_CUTOFF (#PCDATA)>
<!ELEMENT LONG_CUTOFF (#PCDATA)>
<!ELEMENT METHOD (#PCDATA)>

<!--
Least Square Removed Profile's surface parameters information
	Pa: required. Arithmetical mean deviation of the assessed profile 
	Pq: required. Root mean square deviation of the assessed profile 
	Psk: required. Skewness of the assessed profile 
	Pku: required. Kurtosis of the assessed profile 
	Pz: required. Maximum height of profile  
	PDq: required. root mean square slope of the assessed profile
	PSm: required. mean width of the profile elements
	Pc: required. mean height of the profile elements
	Pt: required. Total Height of Profile 
	Pp: required. Maximum Profile Peak Height 
	Pv: required. Maximum Profile Valley Depth 
	UNITS: required. units m, mm, um, nm
 SM_SETTING: required. Indicate Heigh and spacing discrimination for Sm Calculation
 PC_SETTING: required. Indicate Heigh and spacing discrimination for Pc Calculation
-->
<!ELEMENT LSQ_REMOVED_PROFILE (LSQ_REMOVED_PROFILE_SURFACE_PARAMETERS?)>
<!ELEMENT LSQ_REMOVED_PROFILE_SURFACE_PARAMETERS (PA,PQ,PSK,PKU,PZ,PDq,PSm,Pc,Pt,Pp,Pv,UNITS,SM_SETTING,PC_SETTING)>
<!ELEMENT PA (#PCDATA)>
<!ELEMENT PQ (#PCDATA)>
<!ELEMENT PSK (#PCDATA)>
<!ELEMENT PKU (#PCDATA)>
<!ELEMENT PZ (#PCDATA)>
<!ELEMENT PDq (#PCDATA)>
<!ELEMENT PSm (#PCDATA)>
<!ELEMENT Pc (#PCDATA)>
<!ELEMENT Pt (#PCDATA)>
<!ELEMENT Pp (#PCDATA)>
<!ELEMENT Pv (#PCDATA)>
<!ELEMENT SM_SETTING (#PCDATA)>

<!ELEMENT PC_SETTING (#PCDATA)>

<!--
Primary Profile's surface parameters information
	Pa: required. Arithmetical mean deviation of the assessed profile 
	Pq: required. Root mean square deviation of the assessed profile 
	Psk: required. Skewness of the assessed profile 
	Pku: required. Kurtosis of the assessed profile 
	Pz: required. Maximum height of profile  
	PDq: required. root mean square slope of the assessed profile
	PSm: required. mean width of the profile elements
	Pc: required. mean height of the profile elements
	Pt: required. Total Height of Profile 
	Pp: required. Maximum Profile Peak Height 
	Pv: required. Maximum Profile Valley Depth 
	SHORT_CUTOFF_PROFILE_NUMBPOINTS: required. number of data points of the primary profile
      SHORT_CUTOFF_PROFILE_DATA_POINT_VALUES: required. data points of the primary profile
	UNITS: required. units m, mm, um, nm
	SHORT_CUTOFF_PROFILE_NUMBPOINTS: required. number of data points 
-->
<!ELEMENT SHORT_CUTOFF_PROFILE (SHORT_CUTOFF_PROFILE_SURFACE_PARAMETERS?, SHORT_CUTOFF_PROFILE_NUMBPOINTS,SHORT_CUTOFF_PROFILE_DATA_POINT_VALUES)>
<!ELEMENT SHORT_CUTOFF_PROFILE_SURFACE_PARAMETERS (PA,PQ,PSK,PKU,PZ,PDq,PSm,Pc,Pt,Pp,Pv,UNITS,SM_SETTING,PC_SETTING)>
<!ELEMENT SHORT_CUTOFF_PROFILE_NUMBPOINTS (#PCDATA)>
<!ELEMENT SHORT_CUTOFF_PROFILE_DATA_POINT_VALUES (#PCDATA)>

<!--
Raw Profile's surface parameters information
	Pa: required. Arithmetical mean deviation of the assessed profile 
	Pq: required. Root mean square deviation of the assessed profile 
	Psk: required. Skewness of the assessed profile 
	Pku: required. Kurtosis of the assessed profile 
	Pz: required. Maximum height of profile  
	PDq: required. root mean square slope of the assessed profile
	PSm: required. mean width of the profile elements
	PC: required. mean width of the profile elements
	Pt: required. Total Height of Profile 
	Pp: required. Maximum Profile Peak Height 
	Pv: required. Maximum Profile Valley Depth 
	UNITS: required. units m, mm, um, nm
-->
<!ELEMENT RAW_PROFILE (RAW_PROFILE_SURFACE_PARAMETERS?)>
<!ELEMENT RAW_PROFILE_SURFACE_PARAMETERS (PA,PQ,PSK,PKU,PZ,PDq,PSm,PC,Pt,Pp,Pv, UNITS,SM_SETTING,PC_SETTING)>

<!--
Roughness Profile's surface parameters information
	Ra: required. Arithmetical mean deviation of the assessed profile 
	Rq: required. Root mean square deviation of the assessed profile 
	Rsk: required. Skewness of the assessed profile 
	Rku: required. Kurtosis of the assessed profile 
	Rz: required. Maximum height of profile  
	RDq: required. root mean square slope of the assessed profile
	RSm: required. mean width of the profile elements
	Rc: required. mean width of the profile elements
	Rt: required. Total Height of Profile 
	Rp: required. Maximum Profile Peak Height 
	Rv: required. Maximum Profile Valley Depth 
       UNITS: required. units m, mm, um, nm
	ROUGHNESS_NUMPOINTS: required. number of data points 
	ROUGHNESS_DATA_POINT_VALUES: required. Roughness data points
	UNITS: required. units m, mm, um, nm
	CALCULATION_TYPE: required. indicate if the calculation is based on the sampling length or the evaluation length 
-->
<!ELEMENT ROUGHNESS (ROUGHNESS_SURFACE_PARAMETERS?,ROUGHNESS_NUMPOINTS,ROUGHNESS_DATA_POINT_VALUES)>
<!ELEMENT ROUGHNESS_SURFACE_PARAMETERS (RA,RQ,RSK,RKU,RZ,RDq,RSm,Rc,Rt,Rp,Rv,UNITS, CALCULATION_TYPE,SM_SETTING,PC_SETTING)>
<!ELEMENT RA (#PCDATA)>
<!ELEMENT RQ (#PCDATA)>
<!ELEMENT RSK (#PCDATA)>
<!ELEMENT RKU (#PCDATA)>
<!ELEMENT RZ (#PCDATA)>
<!ELEMENT RDq (#PCDATA)>
<!ELEMENT RSm (#PCDATA)>
<!ELEMENT Rc (#PCDATA)>
<!ELEMENT Rt (#PCDATA)>
<!ELEMENT Rp (#PCDATA)>
<!ELEMENT Rv (#PCDATA)>
<!ELEMENT ROUGHNESS_NUMPOINTS (#PCDATA)>
<!ELEMENT ROUGHNESS_DATA_POINT_VALUES (#PCDATA)>
<!ELEMENT CALCULATION_TYPE (#PCDATA)>

<!--
Waviness Profile's surface parameters information
	Wa: required. Arithmetical mean deviation of the assessed profile 
	Wq: required. Root mean square deviation of the assessed profile 
	Wsk: required. Skewness of the assessed profile 
	Wku: required. Kurtosis of the assessed profile 
	Wz: required. Maximum height of profile  
	WDq: required. root mean square slope of the assessed profile
	WSm: required. mean width of the profile elements
	Wc: required. mean height of the profile elements
	Wt: required. Total Height of Profile 
	Wp: required. Maximum Profile Peak Height 
	Wv: required. Maximum Profile Valley Depth 
       UNITS: required. units m, mm, um, nm
	WAVINESS_NUMPOINTS: required. number of data points 
	WAVINESS_DATA_POINT_VALUES: required. waviness data points
	CALCULATION_TYPE: required. indicate if calculation is based on the sampling length or the evaluation length 
-->
<!ELEMENT WAVINESS (WAVINESS_SURFACE_PARAMETERS?,WAVINESS_NUMPOINTS,WAVINESS_DATA_POINT_VALUES)>
<!ELEMENT WAVINESS_SURFACE_PARAMETERS (WA,WQ,WSK,WKU,WZ,WDq,WSm,Wc,Wt,Wp,Wv, UNITS, CALCULATION_TYPE,SM_SETTING,PC_SETTING)>
<!ELEMENT WA (#PCDATA)>
<!ELEMENT WQ (#PCDATA)>
<!ELEMENT WSK (#PCDATA)>
<!ELEMENT WKU (#PCDATA)>
<!ELEMENT WZ (#PCDATA)>
<!ELEMENT WDq (#PCDATA)>
<!ELEMENT Wt (#PCDATA)>
<!ELEMENT Wp (#PCDATA)>
<!ELEMENT Wv (#PCDATA)>
<!ELEMENT WSm (#PCDATA)>
<!ELEMENT Wc (#PCDATA)>
<!ELEMENT WAVINESS_NUMPOINTS (#PCDATA)>
<!ELEMENT WAVINESS_DATA_POINT_VALUES (#PCDATA)>

<!--
Statistical Analysis information
	PSD: optional. Power Spectral Density
	AUTOCORRELATION: optional. Auto Correlation
-->
<!ELEMENT STATISTICAL_ANALYSIS (PSD?,AUTOCORRELATION?)>

<!--
Power Spectral Density information
	PSD_PROFILE_TYPE: required. indicate which type of a profile, such as primary, waviness or roughess, is applied by PSD 
	PSD_METHOD: required. Method to calculate PSD
	PSD_NUMPOINTS: required. Number of PSD data points
	FREQUENCY_RESOLUTION: required. fequency resolution of PSD
	Rq_SQUARE: required. Square of rms. This must be equal to 2 times PSD area 
	TWO_PSD_AREA: required.  Twice Area under PSD curve
	PSD_DATA_POINT_VALUES: required. Data points of PSD
-->
<!ELEMENT PSD (PSD_PROFILE_TYPE,PSD_METHOD,PSD_NUMPOINTS,FREQUENCY_RESOLUTION,Rq_SQUARE,TWO_PSD_AREA,PSD_DATA_POINT_VALUES)>
<!ELEMENT PSD_PROFILE_TYPE (#PCDATA)>
<!ELEMENT PSD_METHOD (#PCDATA)>
<!ELEMENT PSD_NUMPOINTS (#PCDATA)>
<!ELEMENT FREQUENCY_RESOLUTION (#PCDATA)>
<!ELEMENT Rq_SQUARE (#PCDATA)>
<!ELEMENT TWO_PSD_AREA (#PCDATA)>
<!ELEMENT PSD_DATA_POINT_VALUES (#PCDATA)>

<!--
Power Spectral Density information
	AUTOC_PROFILE_TYPE: required. indicate which type of a profile, such as primary, waviness or roughess, is applied by Auto Correlation 
	AUTOC_METHOD: required. Method to calculate PSD
	AUTOC_NUMPOINTS: required. Number of Auto Correlation data points
	AUTOC_DATA_POINT_VALUES: required. Data points of Auto Correlation
-->
<!ELEMENT AUTOCORRELATION (AUTOC_PROFILE_TYPE,AUTOC_METHOD,AUTOC_NUMPOINTS,AUTOC_DATA_POINT_VALUES)>
<!ELEMENT AUTOC_PROFILE_TYPE (#PCDATA)>
<!ELEMENT AUTOC_METHOD (#PCDATA)>
<!ELEMENT AUTOC_NUMPOINTS (#PCDATA)>
<!ELEMENT AUTOC_DATA_POINT_VALUES (#PCDATA)>

=== giacomomarchioro/phdthesis/jupyter notebook/data.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet type="text/xsl" href="data.xsl"?>
<!DOCTYPE DATA SYSTEM "data.dtd">
<DATA>
<PART>
<PART_NAME>D_cors</PART_NAME>
<PART_DATE>1998-03-01 00:00:00.0</PART_DATE>
<PART_MANUFACTURER>ASME B46</PART_MANUFACTURER>
<PART_DESCRIPTION>Type-D roughness specimen</PART_DESCRIPTION>
</PART>
<PROCESS><PROCESS_NAME>Scaled, Measured Data</PROCESS_NAME>
</PROCESS>
<MEASUREMENT><MEASUREMENT_INSTRUMENT_TYPE>N/A</MEASUREMENT_INSTRUMENT_TYPE>
</MEASUREMENT>
<DATAFILE>
<FILENAME>D_cors.sdf</FILENAME>
<UNITS>um</UNITS>
<NUMPOINTS>8000</NUMPOINTS>
<SPACING>0.5</SPACING>
<KCAL>1um/mv</KCAL>
<DATA_TYPE>2D</DATA_TYPE>
<DATA_POINT_VALUES>-1.7214
-1.7684000000000002
-1.8228000000000002
-1.9152
-1.8938000000000001
-1.8649
-1.7903
-1.7539
-1.7247000000000001
-1.7185000000000001
-1.7352
-1.782
-1.8214000000000001
-1.8757000000000001
-1.9379000000000002
-2.0303
-2.1378
-2.2148000000000003
-2.2237
-2.2175000000000002
-2.2113
-2.2356000000000003
-2.2218
-2.2078
-2.1789
-2.1651000000000002
-2.174
-2.1829
-2.1918
-2.2162
-2.278
-2.3553
-2.3794
-2.3958
-2.4202
-2.4518
-2.4683
-2.4696000000000002
-2.471
-2.4647
-2.4661
-2.5055
-2.5447
-2.5688
-2.5852
-2.5715000000000003
-2.5577
-2.559
-2.568
-2.5998
-2.6315
-2.686
-2.7025
-2.7114000000000003
-2.7355
-2.7671
-2.8292
-2.8003
-2.7865
-2.7728
-2.7587
-2.7374
-2.7009000000000003
-2.6795
-2.7036000000000002
-2.7733000000000003
-2.8049
-2.8365
-2.8454
-2.8471
-2.8711
-2.8800000000000003
-2.8965
-2.9206000000000003
-2.9295
-2.9233000000000002
-2.9246000000000003
-2.9489
-2.9881
-3.0197000000000003
-3.0289
-3.0454000000000003
-3.077
-3.1162
-3.1024000000000003
-3.0584000000000002
-3.0143
-2.9549000000000003
-2.926
-2.9122000000000003
-2.9211
-2.9603
-2.9919000000000002
-2.9932000000000003
-2.9795000000000003
-2.9808000000000003
-2.9976000000000003
-2.9914
-2.9546
-2.903
-2.8663000000000003
-2.8449
-2.8084000000000002
-2.7644
-2.7125
-2.676
-2.6547
-2.6409000000000002
-2.6344000000000003
-2.6512000000000002
-2.6979
-2.7374
-2.769
-2.7703
-2.7717
-2.7276000000000002
-2.6682
-2.6242
-2.595
-2.6039000000000003
-2.6282
-2.6447000000000003
-2.646
-2.6171
-2.5958
-2.5742000000000003
-2.5831
-2.5923000000000003
-2.6012
-2.572
-2.5204
-2.4685
-2.4472
-2.4410000000000003
-2.4272
-2.3756
-2.3237
-2.2416
-2.2051000000000003
-2.2064
-2.2153
-2.2167
-2.2335000000000003
-2.2651
-2.274
-2.2678000000000003
-2.254
-2.2402
-2.2189
-2.1972
-2.1835
-2.1697
-2.1559
-2.1270000000000002
-2.0981
-2.0538000000000003
-2.0022
-1.9808000000000001
-1.9516
-1.9303000000000001
-1.9165
-1.9027
-1.9041000000000001
-1.8903
-1.869
-1.8627
-1.8717000000000001
-1.8349000000000002
-1.7833
-1.7314
-1.7101000000000002
-1.7039000000000002
-1.6976
-1.6687
-1.6247
-1.5804
-1.5363
-1.4996
-1.4707000000000001
-1.4493
-1.4507
-1.4747000000000001
-1.4761
-1.4623000000000002
-1.441
-1.4045
-1.3526
-1.3086
-1.2645
-1.2278
-1.2064000000000001
-1.1319000000000001
-1.0727
-1.0284
-1.0070000000000001
-0.9781000000000001
-0.9265
-0.8746
-0.8608
-0.8622000000000001
-0.8409000000000001
-0.8119000000000001
-0.7752
-0.7614000000000001
-0.7628
-0.7792
-0.7428
-0.6682
-0.5712
-0.48910000000000003
-0.39180000000000004
-0.33990000000000004
-0.3034
-0.2821
-0.29860000000000003
-0.3226
-0.3164
-0.30260000000000004
-0.2813
-0.2524
-0.2235
-0.1716
-0.12000000000000001
-0.060500000000000005
-0.0089
0.0354
0.041600000000000005
0.0403
0.054
0.09050000000000001
0.1273
0.14100000000000001
0.17
0.22160000000000002
0.29610000000000003
0.37070000000000003
0.4148
0.45880000000000004
0.48040000000000005
0.49420000000000003
0.5307000000000001
0.5444
0.5888
0.6404000000000001
0.7225
0.8046000000000001
0.879
0.9233
0.9522
0.9887
1.0405
1.077
1.1135000000000002
1.1348
1.1716
1.1702000000000001
1.1916
1.2054
1.2343
1.2556
1.2848000000000002
1.3213000000000001
1.411
1.5082
1.5901
1.6798000000000002
1.7544000000000002
1.8136
1.873
1.917
1.9538000000000002
1.9751
1.9738
1.9876
1.9862000000000002
2.0076
2.0062
2.0351
2.0719000000000003
2.1159
2.1373
2.1662
2.2029
2.2697000000000003
2.3367
2.3807
2.4250000000000003
2.4691
2.5134000000000003
2.5574000000000003
2.5788
2.5472
2.6369000000000002
2.7263
2.8617000000000004
2.9665000000000004
3.0332000000000003
3.0927000000000002
3.1065
3.1656
3.2251000000000003
3.2691000000000003
3.3134
3.365
3.3864
3.3850000000000002
3.4369
3.5266
3.6390000000000002
3.7514000000000003
3.8487
3.9154
3.9292000000000002
3.9354
3.9416
3.9784
4.052700000000001
4.1348
4.1867
4.2459
4.2978000000000005
4.3569
4.4164
4.4907
4.5728
4.6323
4.646
4.6371
4.6812000000000005
4.7633
4.8376
4.8895
4.895700000000001
4.8944
4.9006
4.937
5.0192000000000005
5.1013
5.1454
5.1818
5.211
5.2475000000000005
5.268800000000001
5.244800000000001
5.251
5.2724
5.3242
5.3607000000000005
5.3745
5.365600000000001
5.3186
5.2567
5.209700000000001
5.2540000000000004
5.3056
5.3421
5.371300000000001
5.3775
5.3837
5.3518
5.312600000000001
5.288600000000001
5.3024000000000004
5.331300000000001
5.3223
5.2832
5.213500000000001
5.1818
5.1729
5.1486
5.1246
5.1081
5.1143
5.1356
5.1721
5.2089
5.2226
5.236400000000001
5.2351
5.211
5.2324
5.2537
5.2826
5.2964
5.3180000000000005
5.3394
5.330500000000001
5.2834
5.2518
5.2278
5.1959
5.1416
5.0719
5.063000000000001
5.076700000000001
5.1132
5.15
5.1864
5.2153
5.2521
5.2507
5.2264
5.157
5.034
5.0403
5.0543000000000005
5.090800000000001
5.1046000000000005
5.125900000000001
5.1397
5.1459
5.1143
5.0597
4.9827
4.8676
4.8965000000000005
4.925400000000001
4.9543
4.9606
4.9668
4.9579
4.933800000000001
4.8641000000000005
4.794700000000001
4.8236
4.8373
4.8587
4.8346
4.7801
4.7636
4.7622
4.7533
4.752000000000001
4.743
4.734100000000001
4.7403
4.7617
4.783
4.8044
4.8260000000000005
4.8852
4.9446
4.9962
5.0481
5.0921
5.1135
5.1121
5.1183000000000005
5.1094
5.1081
5.0840000000000005
5.0521
5.0738
5.0875
5.1013
5.0924000000000005
5.0303
4.9379
4.891100000000001
4.8441
4.7974000000000006
4.7655
4.7641
4.7628
4.7236
4.7071000000000005
4.736000000000001
4.7879000000000005
4.809200000000001
4.8306000000000004
4.8292
4.8128
4.7884
4.6885
4.7252
4.7314
4.806
4.8122
4.803
4.779
4.7776000000000005
4.7763
4.774900000000001
4.7736
4.8025
4.8163
4.8379
4.8441
4.8273
4.7882
4.7414000000000005
4.702
4.6552
4.593100000000001
4.5388
4.4993
4.4526
4.4283
4.3967
4.387700000000001
4.3788
4.3623
4.338
4.2988
4.1913
4.1975
4.1962
4.2099
4.2010000000000005
4.2148
4.2135
4.2121
4.2032
4.1943
4.1854000000000005
4.184
4.1978
4.204000000000001
4.1951
4.1708
4.131600000000001
4.0773
4.0303
3.9987000000000004
3.9592
3.9200000000000004
3.8654
3.7733000000000003
3.7339
3.6871
3.6477000000000004
3.6009
3.5539
3.5223
3.5058000000000002
3.5045
3.4955000000000003
3.4866
3.4623000000000004
3.4685
3.4747000000000003
3.4583000000000004
3.4266
3.395
3.3631
3.3164000000000002
3.2467
3.2075
3.2062
3.2124
3.1805000000000003
3.1564
3.1248
3.0854000000000004
3.0462000000000002
2.9919000000000002
2.9449
2.936
2.9573
2.9635000000000002
2.9773
2.9684
2.9368000000000003
2.8898
2.8279
2.7884
2.7795
2.7857000000000003
2.7768
2.7074000000000003
2.6377
2.5907
2.5817
2.5653
2.5488
2.4942
2.4399
2.4004000000000003
2.384
2.3675
2.3434
2.3040000000000003
2.2648
2.2483
2.2394000000000003
2.2075
2.1381
2.0381
1.923
1.8684
1.8595000000000002
1.8657000000000001
1.8492000000000002
1.7947000000000002
1.7176
1.6479000000000001
1.6009
1.5542
1.5150000000000001
1.4604000000000001
1.4288
1.3894
1.3653
1.3413000000000002
1.3248
1.3005
1.2537
1.2372
1.2208
1.1964000000000001
1.1724
1.1256000000000002
1.1167
1.1151
1.1216000000000002
1.12
1.1265
1.1402
1.1540000000000001
1.1527
1.1283
1.1119
1.0802
1.0411000000000001
0.9487000000000001
0.9243
0.8852000000000001
0.8989
0.9052
0.9114000000000001
0.9025000000000001
0.9011
0.8922
0.8376
0.8668
0.9184
1.0005
1.0446
1.0735000000000001
1.0570000000000002
1.0330000000000001
0.9787
0.9770000000000001
0.9606
0.9365
0.9049
0.8503000000000001
0.8036000000000001
0.749
0.649
0.6098
0.616
0.6223000000000001
0.6058
0.5893
0.5725
0.5712
0.5928
0.599
0.6128
0.5885
0.5266000000000001
0.4796
0.4707
0.49200000000000005
0.5061
0.5045000000000001
0.46530000000000005
0.44120000000000004
0.4777
0.5142
0.5585
0.595
0.6239
0.6531
0.6517000000000001
0.6274000000000001
0.5504
0.5109
0.502
0.5158
0.5296000000000001
0.5282
0.5345
0.5636
0.6379
0.6898000000000001
0.7339
0.7628
0.7919
0.8284
0.8573000000000001
0.8409000000000001
0.8017000000000001
0.7774000000000001
0.7684000000000001
0.7747
0.7657
0.7493000000000001
0.7252000000000001
0.7009000000000001
0.6768000000000001
0.6452
0.6817000000000001
0.7412000000000001
0.8155
0.89
0.9495
0.9784
0.9922000000000001
0.9908
0.9516
0.8819
0.9033
0.9322
0.9614
0.9751000000000001
0.9814
0.9724
0.9633
0.9849
1.0062
1.02
1.0413000000000001
1.0324
1.084
1.1283
1.1800000000000002
1.2016
1.2078
1.1759000000000002
1.0911
1.0519
1.1035000000000001
1.1856
1.2451
1.3118
1.3256000000000001
1.3396000000000001
1.361
1.3823
1.381
1.3796000000000002
1.3783
1.3845
1.3907
1.3818000000000001
1.3423
1.288
1.2486000000000002
1.2397
1.2383
1.2294
1.2054
1.1737
1.1343
1.1027
1.0632000000000001
1.0467
1.0227
0.9986
0.9746
0.9503
0.9414
0.9249
0.9008
0.8844000000000001
0.86
0.8133
0.7663000000000001
0.6968000000000001
0.6347
0.5650000000000001
0.5107
0.4258
0.4093
0.38530000000000003
0.3764
0.3521
0.3356
0.2888
0.24180000000000001
0.1951
0.15560000000000002
0.13920000000000002
0.1075
0.0835
0.028900000000000002
-0.0408
-0.08750000000000001
-0.1192
-0.151
-0.2053
-0.19160000000000002
-0.2081
-0.2018
-0.2262
-0.2351
-0.2667
-0.32130000000000003
-0.3907
-0.42260000000000003
-0.4315
-0.4329
-0.45690000000000003
-0.48100000000000004
-0.5431
-0.5974
-0.6369
-0.6685
-0.7382000000000001
-0.7395
-0.7257
-0.6739
-0.6525000000000001
-0.6387
-0.6779000000000001
-0.7325
-0.8173
-0.9019
-0.9262
-0.9654
-0.9895
-1.0138
-1.0303
-1.0543
-1.0859
-1.1027
-1.1192
-1.1281
-1.1521000000000001
-1.1991
-1.2156
-1.217
-1.1881000000000002
-1.1664
-1.1451
-1.1313
-1.1251
-1.1340000000000001
-1.1581000000000001
-1.2278
-1.2064000000000001
-1.2456
-1.2699
-1.3621
-1.4545000000000001
